[package]
name = "linprog"
version = "0.3.0"
authors = ["jonathansc <jonathansc@airmail.cc>"]
edition = "2018"
license = "MIT"
description = "A linear programming library."
[dependencies]
uuid = { version = "0.4", features = ["v4"] }